GET  http://localhost:3000/users

###
GET  http://localhost:3000/users/66c48f6152d35a31880785de

###
PATCH   http://localhost:3000/add-partner/66c48f6152d35a31880785de
Content-Type: application/json

{
   "partner": "66c48f6752d35a318807860e"
}

###
PATCH   http://localhost:3000/delete-partner/66c48f6152d35a31880785de
Content-Type: application/json

{
   "partner": "66c48f6752d35a318807860e"
}

###
GET http://localhost:3000/token

###
DELETE  http://localhost:3000/logout

###
POST http://localhost:3000/login
Content-Type: application/json

{
   "email-username-input": "test",
   "password": "1234567"
}

###
POST  http://localhost:3000/register
Content-Type: application/json

{
   "name": "tester4",
   "username": "test4",
   "email": "tester4@gmail.com",
   "password": "1234567",
   "confirm-password": "1234567"
}


###
PATCH  http://localhost:3000/users/668904c9919099a6cea88c82
Content-Type: application/json

{
   "nama" : "era",
   "email": "era@gmail.com"
}