import React from "react";
const columns = [
  {name: "NAME", uid: "name", sortable: true},
  {name: "USERNAME", uid: "username", sortable: true},
  {name: "EMAIL", uid: "email"},
  {name: "MATCH TOTAL", uid: "match total"},
  {name: "WIN - LOSE", uid: "win - lose"},
  {name: "ACTIONS", uid: "actions"},
];


const users = [
  {
    id: 1,
    name: "Tony Reichert",
    username: "a",
    email: "tony.reichert@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
  {
    id: 2,
    name: "Zoey Lang",
    username: "a",
    email: "zoey.lang@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
  {
    id: 3,
    name: "Jane Fisher",
    username: "a",
    email: "jane.fisher@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
  {
    id: 4,
    name: "William Howard",
    username: "a",
    email: "william.howard@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
  {
    id: 5,
    name: "Kristen Copper",
    username: "a",
    email: "kristen.cooper@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
  {
    id: 6,
    name: "Brian Kim",
    username: "a",
    email: "brian.kim@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
  {
    id: 7,
    name: "Michael Hunt",
    username: "a",
    email: "michael.hunt@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
  {
    id: 8,
    name: "Samantha Brooks",
    username: "a",
    email: "samantha.brooks@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
  {
    id: 9,
    name: "Frank Harrison",
    username: "a",
    email: "frank.harrison@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
  {
    id: 10,
    name: "Emma Adams",
    username: "a",
    email: "emma.adams@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
  {
    id: 11,
    name: "Brandon Stevens",
    username: "a",
    email: "brandon.stevens@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
  {
    id: 12,
    name: "Megan Richards",
    username: "a",
    email: "megan.richards@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
  {
    id: 13,
    name: "Oliver Scott",
    username: "a",
    email: "oliver.scott@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
  {
    id: 14,
    name: "Grace Allen",
    username: "a",
    email: "grace.allen@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
  {
    id: 15,
    name: "Noah Carter",
    username: "a",
    email: "noah.carter@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
  {
    id: 16,
    name: "Ava Perez",
    username: "a",
    email: "ava.perez@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
  {
    id: 17,
    name: "Liam Johnson",
    username: "a",
    email: "liam.johnson@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
  {
    id: 18,
    name: "Sophia Taylor",
    username: "a",
    email: "sophia.taylor@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
  {
    id: 19,
    name: "Lucas Harris",
    username: "a",
    email: "lucas.harris@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
  {
    id: 20,
    name: "Mia Robinson",
    username: "a",
    email: "mia.robinson@example.com",
    matchTotal: 20,
    win: 15,
    lose: 5,
  },
];

export {columns, users};
